spring.application.name=productos
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_db
spring.datasource.username=postgres
spring.datasource.password=1911
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.time-zone=America/Bogota
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
spring.web.error.include-stacktrace=never
spring.web.error.include-message=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Sin esto data.sql se ejecuta ANTES de que JPA cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT Config
jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-aqui
jwt.expiration-ms=86400000

# CORS (permite peticiones desde el frontend)
spring.web.cors.allowed-origins=http://localhost:5173